### ISSUE TITLE
Fail at SalmonTE test

### ISSUE THREAD

**Issue by bioysu** [hyunhwaj/SalmonTE#16]
I tried to run SalmonTE with command as following:
python3.6 /pfs1/liuguanghui/suyao/tools/SalmonTE/SalmonTE.py test --inpath=/pfs1/liuguanghui/suyao/project/lncRNA/output2/SalmonTE/HOMOP7_H9P7/Output/SalmonTE_output --outpath=/pfs1/liuguanghui/suyao/project/lncRNA/output2/SalmonTE/HOMOP7_H9P7/Output/SalmonTE_statistical_test --tabletype=csv --figtype=png
I got error like this:
Error in mutate_impl(.data, dots) : Evaluation error: 0 (non-NA) cases.
Calls: SalmonTE ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl -> .Call
Execution halted
Could you tell me how to fix it?

**Comment by hyunhwaj** [comment]
@bioysu, 

Can you zip the output folder and send it to hyunhwaj@bcm.edu?

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
@bioysu, as I wrote in the email, there is no phenotype/trait information for each sample in the `phenotype.csv`, so that is the reason you could see the error. I will try to add an error message to avoid confusion about this case.

Thanks for your reporting.

Hyun-Hwan Jeong
