### ISSUE TITLE
Failed SalmonTE example run

### ISSUE THREAD

**Issue by wescaiju** [hyunhwaj/SalmonTE#19]
I followed the example code and ran
`SalmonTE.py quant --reference=hs ~/programs/SalmonTE/example/`

However, I got this error:
`KeyError in line 3 of /home/wc376/programs/SalmonTE/snakemake/Snakefile.paired:
'index'
  File "/home/wc376/programs/SalmonTE/snakemake/Snakefile.paired", line 3, in <module>
Will exit after finishing currently running jobs.
2018-08-26 18:23:14,773 Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message`

Any ideas? I am running with Python 3.5.1, snakemake-5.2.2, pandas-0.23.4, docopt-0.6.2

**Comment by hyunhwaj** [comment]
Hello @wescaiju,

I can't generate the same message using the command-line. One thing I am suspecting is the version of `snakemake` is `5.2.2`, and `SalmonTE` is not guaranteed to run with the latest version of `snakemake`. Can you downgrade `snakemake` to 5.1.5 and rerun it again? Please refer this link if you don't know how to downgrade the version of `snakemake`. https://github.com/hyunhwaj/SalmonTE/issues/14#issuecomment-408705766

Best Regards,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
I close this issue because it is been a while since I have asked, but no response.
