### ISSUE TITLE
SalmonTE crashes on macOS.

### ISSUE THREAD

**Issue by hyunhwaj** [hyunhwaj/SalmonTE#2]
It is a follow-up to #1 which was initiated by @sarah872. That issue was opened because of @sarah872 is looking for another option to run. Now the issue is resolved (I believe so), and I will finalize if we can say **OKAY**.

Thanks for the reporting, @sarah872.

Hyun-Hwan Jeong

**Comment by sarah872** [comment]
the command
`git clone https://github.com/docopt/docopt
cd docopt
python3 setup.py install`

solved the problem and SalmonTE is running perfectly now!

**Comment by hyunhwaj** [comment]
Hello @sarah872,

Did you finish to run `SalmonTE`on macOS? Please let me know whether it works.
