### ISSUE TITLE
mapping rate

### ISSUE THREAD

**Issue by wjyzidane** [hyunhwaj/SalmonTE#22]
Hello,

I wonder if there is a way to pull out the mapping rate of each sample from SalmonTE?

**Comment by hyunhwaj** [comment]
@wjyzidane 

Sorry for the late response. There is a manual way to get the mapping rate, but I plan to support this feature! 

Thanks for your patients.

Hyun-Hwan Jeong

**Comment by wjyzidane** [comment]
Thanks and look forward!

**Comment by hyunhwaj** [comment]
@wjyzidane,

Now it reports the mapping rate, please pull the latest version of SalmonTE. 

Thank you,

Hyun-Hwan Jeong

**Comment by wjyzidane** [comment]
Thanks! I will try it.
