### ISSUE TITLE
what is the expected mapping rate?

### ISSUE THREAD

**Issue by bihuimel** [hyunhwaj/SalmonTE#24]
Thanks for updating the tool. I am curious what the expected "percent mapped" should be for mouse tumor samples? I am getting anywhere from 2-4%, which seems quite low considering there are a lot of TEs in the genome. Is this expected or do I need to adjust any settings? 
Thanks!

**Comment by hyunhwaj** [comment]
@bihuimel, If you are using RNA-Seq in your analysis, the mappability is normal range. RNA-Seq reads tend to be from exon regions, and a few of them are from intronic regions, which TE tend to be located. Therefore, you don't need to do any adjustment for your analysis.

Best Regards,

Hyun-Hwan Jeong
