### ISSUE TITLE
Nothing to be done

### ISSUE THREAD

**Issue by wjyzidane** [hyunhwaj/SalmonTE#4]
Salmon TE runs well on my previous samples but when I run it again today. It is done with nothing output.

![image](https://user-images.githubusercontent.com/34944811/34457619-0a149500-ed84-11e7-8755-93e0ee336ce0.png)

So I wonder if anything is going wrong. Thanks!

**Comment by hyunhwaj** [comment]
I guess this was because all the outputs were created so SalmonTE skipped the quantification. Could you remove or change name of the previous output folder?

**Comment by wjyzidane** [comment]
After I delete the previous folder. The SalmonTE runs well without error info. But there is still no result in the output folder. See my command, process info and output as below:

![qq20180101-1](https://user-images.githubusercontent.com/34944811/34469423-811e5bae-eeec-11e7-95e1-4e6132b3e081.png)

![qq20180101-2](https://user-images.githubusercontent.com/34944811/34469425-96b64ba2-eeec-11e7-9ee6-9d4ba47aa900.png)

![qq20180101-3](https://user-images.githubusercontent.com/34944811/34469427-9934c462-eeec-11e7-879e-dc6be027c064.png)

![qq20180101-4](https://user-images.githubusercontent.com/34944811/34469431-aff4410a-eeec-11e7-8161-2054d7f1fef8.png)

Thanks and Happy New Year!

**Comment by hyunhwaj** [comment]
You can specify the output directory with `--outpath` parameter. Could you please run the below command?

```
./SalmonTE.py quant --reference=hs $file --outpath=test_SalmonTE_output
```

You will see your output files in `test_SalmonTE_output` directory. If you still can't solve the problem once you run the command then I will need your information to figure out the issue:

* What is your version of  `SalmonTE`? If your version is not `0.2` then please update it. You can check your version with `SalmonTe.py --version`
* Which is filename linked to your `$file` variable?

Happy New Year!

Hwan

**Comment by wjyzidane** [comment]
Hi Hwan,

I found the problem. It is suffix. Because my filename is test.fq. When I changed it to test.fastq, it runs well. Thanks a lot!

Jingyi

**Comment by hyunhwaj** [comment]
Thanks for your report. I think people oftentimes use `.fq` suffix, so the suffix will be supported in next version of `SalmonTE`. I will close the issue and let you know once I will update it.

Thank you,

Hwan

**Comment by wjyzidane** [comment]
Thank you!

**Comment by hyunhwaj** [comment]
@wjyzidane,

I have committed 1950aaf7098c3bc39448d51e8b9711ee89dd28e9, andn now `SalmonTE` supports `fq` and `fq.gz` extensions. Please let me know if it does not work for you.

Hyun-Hwan Jeong

**Comment by wjyzidane** [comment]
Thanks so much!

Jingyi
