### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by adomingues** [hyunhwaj/SalmonTE#7]
Hi Hwan,

there was an error when running SalmonTE on my sequencing data:

```sh
SalmonTE.py quant --reference=dr --exprtype=TPM --num_threads=4 --outpath="SalmonTE_output/" wt_Fish_1dpf_rep1_R1.fastq.gz wt_Fish_1dpf_rep1_R2.f
astq.gz
2018-01-29 14:34:40,158 Starting quantification mode
2018-01-29 14:34:40,159 Collecting FASTQ files...
Traceback (most recent call last):
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 262, in <module>
    run(args)
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 216, in run
    param = {**args, **collect_FASTQ_files(args['FILE'])}
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 77, in collect_FASTQ_files
    if get_first_readid(file_a) == get_first_readid(file_b):
  File "/fsimb/groups/imb-kettinggr/tools/salmonTE/0.2/SalmonTE/SalmonTE.py", line 48, in get_first_readid
    return inp.readline().split()[0]
  File "/fsimb/groups/imb-kettinggr/tools/python3/3.6.4/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
(tested on a single paired end sample to isolate the issue)

I traced the issue to the function `get_first_readid` and specifically to the read file call:
https://github.com/hyunhwaj/SalmonTE/blob/57597369a02c28e23e215338f38da6d6a489539e/SalmonTE.py#L47

Changing the encoding fixed it for me ([source](https://stackoverflow.com/a/19706723/1274242)):

```python
def get_first_readid(file_name):
    with open(file_name, "r", encoding="ISO-8859-1") as inp:
        return inp.readline().split()[0]
```

I considered committing a pull request with the fix, but since there was no issue with the provided example files, I am unsure of how general the problem is. I am leaving the solution here in case someone else runs into this problem, or you can can think of a different (more general) way of solving it. 

Other details which might be relevant: 

- `NextSeq` generated data
- fastq.gz files
- linux operating sytem

Cheers.

**Comment by hyunhwaj** [comment]
Thanks for the reporting and sorry for your inconvenience, @adomingues. The issue happened because there is an issue with `.fastq.gz` files and this is also related to #8. I uploaded fixed-script to the GitHub repository.

**Comment by hyunhwaj** [comment]
Hello, @adomingues,

It's been a while I asked you about those issues. I had a super busy with other projects, but now I will have a chance to take the issues soon.  I am wondering you still have an issue with**encoding**. If you don't have any then I can close this issue.

Thank you,

Hyun-Hwan Jeong

**Comment by adomingues** [comment]
Hi @hyunhwaj,

As far as I recall this issue is now gone. You can close it.

**Comment by adomingues** [comment]
I just did it for you :)
